version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-whatTimeToPlay
    restart: unless-stopped
    
    environment:
      # Discord Bot Token（從 .env 載入）
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      
    volumes:
      # 持久化資料
      - ./events.json:/app/events.json
      # 如果需要掛載整個專案目錄（開發模式）
      # - .:/app
    
    # 資源限制（可選）
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    networks:
      - bot-network
    
    # 健康檢查
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('main.py') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge


